# Generated by Django 4.2.20 on 2026-06-13 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=32)),
                ('payload', models.JSONField()),
                ('failure_reason', models.TextField()),
                ('retry_attempts', models.PositiveSmallIntegerField()),
                ('died_at', models.DateTimeField(auto_now_add=True)),
                ('original_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letter_entries', to='jobs.job')),
            ],
            options={
                'db_table': 'dead_letter_queue',
                'ordering': ('-died_at',),
                'indexes': [models.Index(fields=['job_type', 'died_at'], name='dead_letter_job_typ_baefd6_idx'), models.Index(fields=['original_job'], name='dead_letter_origina_9856a9_idx')],
            },
        ),
    ]
