# Generated by Django 4.2.20 on 2026-06-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('process_payment', 'Process Payment'), ('fraud_check', 'Fraud Check'), ('send_notification', 'Send Notification')], max_length=32)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=16)),
                ('payload', models.JSONField()),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='jobs_job_user_id_ec4047_idx'), models.Index(fields=['job_type', 'status'], name='jobs_job_job_typ_3f135c_idx'), models.Index(fields=['priority', 'created_at'], name='jobs_job_priorit_6f43e4_idx')],
            },
        ),
    ]
