# Generated by Django 4.2.20 on 2026-06-12 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchant', models.CharField(max_length=255)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('suspicious', 'Suspicious'), ('rejected', 'Rejected')], max_length=16)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_reasons', models.JSONField(blank=True, default=list)),
                ('processed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ('-processed_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_user_id_443e2d_idx',
            old_name='jobs_job_user_id_ec4047_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_typ_f035dd_idx',
            old_name='jobs_job_job_typ_3f135c_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_priorit_fa057d_idx',
            old_name='jobs_job_priorit_6f43e4_idx',
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
        migrations.AddField(
            model_name='transaction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'processed_at'], name='transaction_user_id_bce096_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'processed_at'], name='transaction_status_d95105_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['job'], name='transaction_job_id_fa9e14_idx'),
        ),
    ]
